### PR TITLE
Update to v1.1.3

### PR DESCRIPTION
**Pull request by edwinnglabs**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by edwinnglabs** [comment]
@conda-forge-admin, please rerender

**Comment by sugatoray** [comment]
@edwinnglabs Thank you for the PR. Would you like to be a co-maintainer of this repository? Please feel free to add yourself to the list of maintainers. 

Also please consider starring the repo. ⭐️

**Comment by edwinnglabs** [comment]
> @edwinnglabs Thank you for the PR. Would you like to be a co-maintainer of this repository? Please feel free to add yourself to the list of maintainers.
> 
> Also please consider starring the repo. ⭐️

I have starred the repo :) Sure, i would like to be a maintainer.  Could you please add me into the list?

**Comment by edwinnglabs** [comment]
> > @edwinnglabs Thank you for the PR. Would you like to be a co-maintainer of this repository? Please feel free to add yourself to the list of maintainers.
> > Also please consider starring the repo. ⭐️
> 
> I have starred the repo :) Sure, i would like to be a maintainer. Could you please add me into the list?

Any comments on this? @sugatoray Trying to update the version to 1.1.3

**Comment by sugatoray** [comment]
> I have starred the repo :) Sure, i would like to be a maintainer. Could you please add me into the list?
> 
> 
> 
> Any comments on this? @sugatoray Trying to update the version to 1.1.3

👉 Please update the PR title to "Update to `v1.1.3`". This way it will be obvious which version was updated with this PR. 

And I have added you as a co-maintainer in this PR. 🎉

**Comment by edwinnglabs** [comment]
Hello @sugatoray any update?

**Comment by sugatoray** [comment]
> Hello @sugatoray any update?

@edwinnglabs 
Glad to have you as co-maintainer.

**Pull request merged**
